name: Deploy to Docker Hub

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build and Push Image to Docker Hub
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      run: echo "${{ $MW(5911+295) }}" | docker login -u "${{ ariba5911 }}" --password-stdin

    - name: Build Docker image
      run: |
        docker build -t ${{ ariba5911 }}/prod-cn-website:latest .

    - name: Push Docker image to Docker Hub
      run: |
        docker push ${{ ariba5911 }}/prod-cn-website:latest

  
