name: Deploy to Docker Hub!

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build and Push Image to Docker Hub
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      run: echo "${{seceretkey.DOCKERHUB_TOKEN }}" | docker login -u "${{ seceretkey.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: |
        docker build -t ${{ seceretkey.DOCKERHUB_USERNAME }}/prod-cn-website:latest .

    - name: Push Docker image to Docker Hub
      run: |
        docker push ${{seceretkey.DOCKERHUB_USERNAME }}/prod-cn-website:latest

